### ISSUE TITLE
ModuleNotFoundError: No module named 'GPT2.load_params'

### ISSUE THREAD

**Issue by zhenhao-huang** [jm12138/CPM-Generate-Pytorch#1]
缺少load_params这个文件

**Comment by jm12138** [comment]
删掉就行，之前忘记删了，已经更新了

**Comment by zhenhao-huang** [comment]
> 删掉就行，之前忘记删了，已经更新了

单卡gpu怎么设置

**Comment by jm12138** [comment]
加载模型时去掉 map_location='cpu' 应该就可以了

**Comment by zhenhao-huang** [comment]
> 加载模型时去掉 map_location='cpu' 应该就可以了
不行

**Comment by jm12138** [comment]
> > 加载模型时去掉 map_location='cpu' 应该就可以了
> > 不行

具体哪里报错，我这边没有这么大的显存的环境来测试

**Comment by zhenhao-huang** [comment]
> > > 加载模型时去掉 map_location='cpu' 应该就可以了
> > > 不行
> 
> 具体哪里报错，我这边没有这么大的显存的环境来测试

没有报错，就是我的gpu没有被占用，占用的是cpu
