### ISSUE TITLE
这个是运行的GPU上面的吗，我怎么感觉它用的是CPU

### ISSUE THREAD

**Issue by unbuilt** [jm12138/CPM-Generate-Pytorch#4]
Sample的时候CPU使用率很高，GPU使用率基本为0？

**Comment by jm12138** [comment]
emm，demo用的是CPU，我没试过GPU跑，因为我手边没有这么大显存的显卡来跑这个模型，你可以改下代码试试切换成GPU来跑，理论上应该是没问题的，

**Comment by dayu1979** [comment]
可以自己改成GPU，不过GPU最好也要24G

**Comment by 1973sir** [comment]
> emm，demo用的是CPU，我没试过GPU跑，因为我手边没有这么大显存的显卡来跑这个模型，你可以改下代码试试切换成GPU来跑，理论上应该是没问题的，

请问怎么改成GPU呢？我把torch.load的map_location改成cuda:4，gpu上会占用部分显存（内存也依然会占用，只是没有之前那么多），但是运算依然在cpu上跑。

**Comment by unbuilt** [comment]
做了修改，目前支持GPU了。
